#ifndef _SHARED_DEFINES
#define _SHARED_DEFINES

#define MODEL_ATTRIB_POSITIONS		0
#define MODEL_ATTRIB_UVS			1
#define MODEL_ATTRIB_NORMALS		2
#define MODEL_ATTRIB_BONE_INDICES	3
#define MODEL_ATTRIB_BONE_WEIGHTS	4

#endif // _SHARED_DEFINES
