#ifndef _SHARED_DEFINES
#define _SHARED_DEFINES

#define PROG_MODEL_ATTRIB_POSITIONS		0
#define PROG_MODEL_ATTRIB_UVS			1
#define PROG_MODEL_ATTRIB_NORMALS		2
#define PROG_MODEL_ATTRIB_BONE_INDICES	3
#define PROG_MODEL_ATTRIB_BONE_WEIGHTS	4

#define PROG_SIMPLE_ATTRIB_POSITIONS	0
#define PROG_SIMPLE_ATTRIB_COLORS		1

#endif // _SHARED_DEFINES
